/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Practive;

public class App {
  
    public static void main(String[] args) {
        int n1 = 89;
        int n2 = 60;
        System.out.println(n1 & n2);
        System.out.println(n1 | n2);
        System.out.println(n1 ^ n2);
      }
}
